services:
  api:
    build: ./api
    ports:
      - "8081:80"    # host:container
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - api

