apiVersion: v1
kind: Service
metadata:
  name: potioncraft-api
  namespace: potioncraft
spec:
  selector:
    app: potioncraft-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

